// src/routes/videos/+page.svelte
<div class="sm:min-h-[98.5vh] min-h-screen">
    <h1 class="pt-20 text-center font-sans font-bold">Videos</h1>

    <div
        class="flex flex-col justify-center items-center gap-5 pt-10 md:gap-20"
    >
        <iframe
            src="https://www.youtube.com/embed/mNagN4GNRXY"
            frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
            title="video1"
            class="md:w-96 md:h-64"
        />
        <iframe
            src="https://www.youtube.com/embed/Zi6Iz1eLNoA"
            frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen
            title="video1"
            class="md:w-96 md:h-64"
        />

        <a
            href="https://www.youtube.com/@anaitvanoian7094"
            class="flex flex-row gap-2 justify-center items-center pt-10 md:pt-0"
            >Watch more videos on <img
                src="./youtube.png"
                alt="youtube"
                width="30px"
            /></a
        >
    </div>
</div>

// app/videos/page.tsx
export default function VideosPage() {
  return (
    <div className="sm:min-h-[98.5vh] min-h-screen">
      <h1 className="pt-20 text-center font-sans font-bold">Videos</h1>

      <div className="flex flex-col justify-center items-center gap-5 pt-10 md:gap-20">
        <iframe
          src="https://www.youtube.com/embed/mNagN4GNRXY"
          frameBorder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          title="video1"
          className="md:w-96 md:h-64 w-full h-60"
        />
        <iframe
          src="https://www.youtube.com/embed/Zi6Iz1eLNoA"
          frameBorder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
          title="video2"
          className="md:w-96 md:h-64 w-full h-60"
        />

        <a
          href="https://www.youtube.com/@anaitvanoian7094"
          target="_blank"
          rel="noopener noreferrer"
          className="flex flex-row gap-2 justify-center items-center py-10 md:pt-0"
        >
          Watch more videos on
          <img src="/youtube.png" alt="youtube" width="30" />
        </a>
      </div>
    </div>
  );
}
