// src/routes/email/+page.svelte
<script>
    // @ts-nocheck
    import emailjs from "@emailjs/browser";
    // @ts-ignore
    import IoIosMail from "svelte-icons/io/IoIosMail.svelte";
    // @ts-ignore
    import IoIosText from "svelte-icons/io/IoIosText.svelte";
    import { theLanguage } from "../../store/store";
    import { onMount } from "svelte";

    let currentLanguage = "g";
    theLanguage.subscribe((value) => {
        currentLanguage = value;
    });

    //fetching envs
    let myObj = {};
    onMount(async () => {
        try {
            const response = await fetch("/api/email");
            if (response.ok) {
                myObj = await response.json();
            } else {
                throw new Error("Failed to fetch data");
            }
        } catch (error) {
            console.error("error", error);
        }
    });

    //sending email and resetting the fields
    let emailState = "";
    let messageState = "";
    let messageSubject = "";

    let sent = false;
    function sendEmail(e) {
        emailjs
            .sendForm(
                myObj.YOUR_SERVICE_ID,
                myObj.YOUR_TEMPLATE_ID,
                e.target,
                myObj.YOUR_PUBLIC_KEY
            )
            .then(
                (result) => {
                    sent = true;
                    console.log("SUCCESS!", result.text);
                    emailState = "";
                    messageState = "";
                    messageSubject = "";
                    setTimeout(() => {
                        sent = false;
                    }, 3000);
                },
                (error) => {
                    console.log("FAILED...", error.text);
                }
            );
    }
</script>

<div class="min-h-screen sm:min-h-[98.5vh]">
    <h1 class="pt-20 text-center font-sans font-bold">
        {#if currentLanguage === "e"}
            Contancts
        {:else}
            Kontakte
        {/if}
    </h1>
    {#if !sent}
        <div class="text-center mt-3">
            <h1 class="rounded bg-green-300/10 text-green-800 text-center">
                Your message was sent
            </h1>
        </div>
    {/if}
    <form
        class="flex flex-col justify-center h-[70vh] sm:h-[80vh] m-10 font-sans md:w-[400px] md:mx-auto"
        on:submit|preventDefault={sendEmail}
    >
        <label
            for="Email"
            class="w-16 flex flex-row items-center gap-2 text-gray-500"
            >Email<IoIosMail /></label
        >
        <input
            type="text"
            class="rounded"
            placeholder={`${
                currentLanguage === "e"
                    ? "provide your email"
                    : "Geben Sie Ihre E-Mail-Adresse an"
            }`}
            name="email"
            bind:value={emailState}
        />
        <label
            for="Name"
            class="w-16 flex flex-row items-center gap-2 text-gray-500"
            >{#if currentLanguage === "e"}
                Name
            {:else}
                Name
            {/if}
        </label>
        <input
            type="text"
            class="rounded"
            placeholder={`${
                currentLanguage === "e"
                    ? "enter your name"
                    : "Geben Sie Ihren Namen ein"
            }`}
            name="name"
            bind:value={messageSubject}
        />
        <label
            for="Message"
            class="mt-10 w-24 flex flex-row items-center gap-1 text-gray-500"
            >{#if currentLanguage === "e"}
                Message
            {:else}
                Nachricht
            {/if}
            <IoIosText /></label
        >
        <textarea
            class="rounded h-40"
            placeholder={`${
                currentLanguage === "e"
                    ? "write your message here"
                    : "Schreibe deine Nachricht hier"
            }`}
            name="message"
            bind:value={messageState}
        />
        <button class="bg-gray-300 rounded-lg mt-2" type="submit" value="Send"
            >{#if currentLanguage === "e"}
                Send
            {:else}
                Schicken
            {/if}
        </button>
    </form>

    <h5 class="text-xs font-serif text-center py-10">
        The website is made by <a
            href="https://www.facebook.com/vladyslav.tsurkanenko"
            class="italic text-blue-900">Vladyslav Tsurkanenko</a
        >
    </h5>
</div>

// app/email/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useLanguage } from "@/libs/zustand"; // Zustand store
import emailjs from "@emailjs/browser";
import { IoIosMail, IoIosText } from "react-icons/io";

export default function EmailPage() {
  const currentLanguage = useLanguage((state) => state.currentLanguage);

  const [emailState, setEmailState] = useState("");
  const [messageState, setMessageState] = useState("");
  const [messageSubject, setMessageSubject] = useState("");
  const [sent, setSent] = useState(false);

  const [myObj, setMyObj] = useState<{
    YOUR_SERVICE_ID?: string;
    YOUR_TEMPLATE_ID?: string;
    YOUR_PUBLIC_KEY?: string;
  }>({});

  // fetch envs from API
  useEffect(() => {
    const fetchEnv = async () => {
      try {
        const response = await fetch("/api/email");
        if (response.ok) {
          const data = await response.json();
          setMyObj(data);
        } else {
          throw new Error("Failed to fetch data");
        }
      } catch (error) {
        console.error("Error", error);
      }
    };
    fetchEnv();
  }, []);

  const sendEmail = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!myObj.YOUR_SERVICE_ID || !myObj.YOUR_TEMPLATE_ID || !myObj.YOUR_PUBLIC_KEY) {
      console.error("EmailJS config missing!");
      return;
    }

    try {
      await emailjs.sendForm(
        myObj.YOUR_SERVICE_ID,
        myObj.YOUR_TEMPLATE_ID,
        e.currentTarget,
        myObj.YOUR_PUBLIC_KEY
      );
      setSent(true);
      setEmailState("");
      setMessageState("");
      setMessageSubject("");
      setTimeout(() => setSent(false), 3000);
    } catch (error) {
      console.error("FAILED...", error);
    }
  };

  return (
    <div className="min-h-screen sm:min-h-[98.5vh]">
      <h1 className="pt-20 text-center font-sans font-bold">
        {currentLanguage === "e" ? "Contacts" : "Kontakte"}
      </h1>

      {sent && (
        <div className="text-center mt-3">
          <h1 className="rounded bg-green-300/10 text-green-800 text-center">
            {currentLanguage === "e"
              ? "Your message was sent"
              : "Ihre Nachricht wurde gesendet"}
          </h1>
        </div>
      )}

      <form
        className="flex flex-col justify-center h-[70vh] sm:h-[80vh] m-10 font-sans md:w-[400px] md:mx-auto"
        onSubmit={sendEmail}
      >
        {/* Email */}
        <label
          htmlFor="email"
          className="w-16 flex flex-row items-center gap-2 text-gray-500"
        >
          Email <IoIosMail />
        </label>
        <input
          type="email"
          id="email"
          name="email"
          value={emailState}
          onChange={(e) => setEmailState(e.target.value)}
          className="rounded"
          placeholder={
            currentLanguage === "e"
              ? "provide your email"
              : "Geben Sie Ihre E-Mail-Adresse an"
          }
          required
        />

        {/* Name */}
        <label
          htmlFor="name"
          className="w-16 flex flex-row items-center gap-2 text-gray-500 mt-2"
        >
          {currentLanguage === "e" ? "Name" : "Name"}
        </label>
        <input
          type="text"
          id="name"
          name="name"
          value={messageSubject}
          onChange={(e) => setMessageSubject(e.target.value)}
          className="rounded"
          placeholder={
            currentLanguage === "e"
              ? "enter your name"
              : "Geben Sie Ihren Namen ein"
          }
          required
        />

        {/* Message */}
        <label
          htmlFor="message"
          className="mt-10 w-24 flex flex-row items-center gap-1 text-gray-500"
        >
          {currentLanguage === "e" ? "Message" : "Nachricht"}
          <IoIosText />
        </label>
        <textarea
          id="message"
          name="message"
          value={messageState}
          onChange={(e) => setMessageState(e.target.value)}
          className="rounded h-40"
          placeholder={
            currentLanguage === "e"
              ? "write your message here"
              : "Schreibe deine Nachricht hier"
          }
          required
        />

        {/* Submit */}
        <button
          type="submit"
          className="bg-gray-300 rounded-lg mt-2 py-1"
        >
          {currentLanguage === "e" ? "Send" : "Schicken"}
        </button>
      </form>

      <h5 className="text-xs font-serif text-center py-10">
        The website is made by{" "}
        <a
          href="https://www.facebook.com/vladyslav.tsurkanenko"
          className="italic text-blue-900"
          target="_blank"
          rel="noopener noreferrer"
        >
          Vladyslav Tsurkanenko
        </a>
      </h5>
    </div>
  );
}
